### ISSUE TITLE
ValueError: Found array with 0 sample(s) (shape=(0, 1)) while a minimum of 1 is required.

### ISSUE THREAD

**Issue by monajalal** [bluemonk482/tdparse#3]
I get this error running your code:

```
[jalal@goku src]$ ./run.sh election naiveseg sklearnSVM
Traceback (most recent call last):
  File "naive-seg.py", line 430, in <module>
    main(args.d)
  File "naive-seg.py", line 407, in main
    features=targettw()
  File "naive-seg.py", line 49, in __init__
    self.w2v=gensim.models.Word2Vec.load(w2vf) 
  File "/scratch/sjn-p2/anaconda/anaconda2/lib/python2.7/site-packages/gensim/models/word2vec.py", line 975, in load
    return super(Word2Vec, cls).load(*args, **kwargs)
  File "/scratch/sjn-p2/anaconda/anaconda2/lib/python2.7/site-packages/gensim/models/base_any2vec.py", line 629, in load
    model = super(BaseWordEmbeddingsModel, cls).load(*args, **kwargs)
  File "/scratch/sjn-p2/anaconda/anaconda2/lib/python2.7/site-packages/gensim/models/base_any2vec.py", line 278, in load
    return super(BaseAny2VecModel, cls).load(fname_or_handle, **kwargs)
  File "/scratch/sjn-p2/anaconda/anaconda2/lib/python2.7/site-packages/gensim/utils.py", line 426, in load
    obj._load_specials(fname, mmap, compress, subname)
  File "/scratch/sjn-p2/anaconda/anaconda2/lib/python2.7/site-packages/gensim/utils.py", line 469, in _load_specials
    setattr(self, attrib, val)
  File "/scratch/sjn-p2/anaconda/anaconda2/lib/python2.7/site-packages/gensim/utils.py", line 1396, in new_func1
    stacklevel=2
DeprecationWarning: Call to deprecated `syn1` (Attribute will be removed in 4.0.0, use self.trainables.syn1 instead).
/scratch/sjn-p2/anaconda/anaconda2/lib/python2.7/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
********************************************************************************
********************************************************************************
---Feature scaling
Scaling features
can't open file ../data/election/output/training
can't open file ../data/election/output/testing
loading features for training
loading features for testing
cross-validation
Traceback (most recent call last):
  File "sklearnSVM.py", line 103, in <module>
    main(output_dir)
  File "sklearnSVM.py", line 81, in main
    clf = CV(x_train, y_train) # Comment this if parameter tuning is not desired
  File "sklearnSVM.py", line 51, in CV
    grid_search.fit(x_train, y_train)
  File "/scratch/sjn-p2/anaconda/anaconda2/lib/python2.7/site-packages/sklearn/model_selection/_search.py", line 639, in fit
    cv.split(X, y, groups)))
  File "/scratch/sjn-p2/anaconda/anaconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 779, in __call__
    while self.dispatch_one_batch(iterator):
  File "/scratch/sjn-p2/anaconda/anaconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 625, in dispatch_one_batch
    self._dispatch(tasks)
  File "/scratch/sjn-p2/anaconda/anaconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 588, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/scratch/sjn-p2/anaconda/anaconda2/lib/python2.7/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 111, in apply_async
    result = ImmediateResult(func)
  File "/scratch/sjn-p2/anaconda/anaconda2/lib/python2.7/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 332, in __init__
    self.results = batch()
  File "/scratch/sjn-p2/anaconda/anaconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 131, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/scratch/sjn-p2/anaconda/anaconda2/lib/python2.7/site-packages/sklearn/model_selection/_validation.py", line 458, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/scratch/sjn-p2/anaconda/anaconda2/lib/python2.7/site-packages/sklearn/svm/classes.py", line 227, in fit
    dtype=np.float64, order="C")
  File "/scratch/sjn-p2/anaconda/anaconda2/lib/python2.7/site-packages/sklearn/utils/validation.py", line 573, in check_X_y
    ensure_min_features, warn_on_dtype, estimator)
  File "/scratch/sjn-p2/anaconda/anaconda2/lib/python2.7/site-packages/sklearn/utils/validation.py", line 462, in check_array
    context))
ValueError: Found array with 0 sample(s) (shape=(0, 1)) while a minimum of 1 is required.
[jalal@goku src]$ 

```

I have 
```
[jalal@goku src]$ which python
/scratch/sjn-p2/anaconda/anaconda2/bin/python
[jalal@goku src]$ python -V
Python 2.7.14 :: Anaconda custom (64-bit)
[jalal@goku src]$ ls ../data/election/
.gitignore          4479563.zip         annotations/        output/             train_id.txt        tweets.tar.gz       
4479563/            README              annotations.tar.gz  test_id.txt         tweets/  
```

**Comment by bwang482** [comment]
Yeah same issue with gensim word2vec model incompatibility. Maybe the people @gensim have better ways of solving this problem than rolling back gensim version.
