### ISSUE TITLE
IndexError: index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by monajalal** [bluemonk482/tdparse#4]
What am I missing?

```
[jalal@goku src]$ mkdir -p ../data/lidong/output/cv
[jalal@goku src]$ ./run.sh lidong tdparse liblinear scale,tune,pred ../data/lidong/parses/lidong.train.conll ../data/lidong/parses/lidong.test.conll
Traceback (most recent call last):
  File "tdparse.py", line 531, in <module>
    main(args.d, args.conll1, args.conll2)
  File "tdparse.py", line 502, in main
    features=targettw()
  File "tdparse.py", line 114, in __init__
    self.w2v=gensim.models.Word2Vec.load(w2vf) 
  File "/scratch/sjn-p2/anaconda/anaconda2/lib/python2.7/site-packages/gensim/models/word2vec.py", line 975, in load
    return super(Word2Vec, cls).load(*args, **kwargs)
  File "/scratch/sjn-p2/anaconda/anaconda2/lib/python2.7/site-packages/gensim/models/base_any2vec.py", line 629, in load
    model = super(BaseWordEmbeddingsModel, cls).load(*args, **kwargs)
  File "/scratch/sjn-p2/anaconda/anaconda2/lib/python2.7/site-packages/gensim/models/base_any2vec.py", line 278, in load
    return super(BaseAny2VecModel, cls).load(fname_or_handle, **kwargs)
  File "/scratch/sjn-p2/anaconda/anaconda2/lib/python2.7/site-packages/gensim/utils.py", line 426, in load
    obj._load_specials(fname, mmap, compress, subname)
  File "/scratch/sjn-p2/anaconda/anaconda2/lib/python2.7/site-packages/gensim/utils.py", line 469, in _load_specials
    setattr(self, attrib, val)
  File "/scratch/sjn-p2/anaconda/anaconda2/lib/python2.7/site-packages/gensim/utils.py", line 1396, in new_func1
    stacklevel=2
DeprecationWarning: Call to deprecated `syn1` (Attribute will be removed in 4.0.0, use self.trainables.syn1 instead).
/scratch/sjn-p2/anaconda/anaconda2/lib/python2.7/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
********************************************************************************
********************************************************************************
---Feature scaling
Scaling features
can't open file ../data/lidong/output/training
can't open file ../data/lidong/output/testing
---Parameter tuning
/scratch/sjn-p2/anaconda/anaconda2/lib/python2.7/site-packages/numpy/lib/function_base.py:1110: RuntimeWarning: Mean of empty slice.
  avg = a.mean(axis)
/scratch/sjn-p2/anaconda/anaconda2/lib/python2.7/site-packages/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "liblinear.py", line 182, in <module>
    main(output_dir, args.ci, args.p)
  File "liblinear.py", line 138, in main
    tunec = TUNE(trfile,cv_trfile,cv_tfile,cv_pfile,cv_truey,id_train)
  File "liblinear.py", line 110, in TUNE
    tunec.append([ci] + CV(str(ci),trfile,cv_trfile,cv_tfile,cv_pfile,cv_truey,id_train))
  File "liblinear.py", line 83, in CV
    f1_two_list.append((metrics.f1_score(y_test, y_predicted, average=None)[0]+metrics.f1_score(y_test, y_predicted, average=None)[-1])/2)
IndexError: index 0 is out of bounds for axis 0 with size 0
[jalal@goku src]$ 


```

**Comment by bwang482** [comment]
Hi Mona, it seems that features are being extracted due to the failure of loading pretrained word embeddings. There seems to be a ongoing issue with gensim Word2Vec model compatibility. The model saved in `w2vf` was trained in a early version of gensim ('1.0.1'). I would suggest to roll back your version of gensim if that's not too much trouble.

**Comment by ankita240796** [comment]
Hi @monajalal were you able to fix this? If so can you please describe the steps used in fixing the issue, Thanks!
