### ISSUE TITLE
 File "/scratch2/debate_tweets/sentiment/tdparse/src/utilities.py", line 175, in traversaltree     positions = [[item for sublist in traversal.bfs_successors(G, target_position).values() for item in sublist] for target_position in target_positions] AttributeError: 'generator' object has no attribute 'values'

### ISSUE THREAD

**Issue by monajalal** [bluemonk482/tdparse#5]
I installed gensim1.0.1 and now I have this error

```
[jalal@goku src]$  ./run.sh lidong tdparse liblinear scale,tune,pred ../data/lidong/parses/lidong.train.conll ../data/lidong/parses/lidong.test.conll
extracting features for training
Traceback (most recent call last):
  File "tdparse.py", line 531, in <module>
    main(args.d, args.conll1, args.conll2)
  File "tdparse.py", line 505, in main
    x_train,y_train=features.lidongfeat('../data/'+d+'/training/', train_conllpath)
  File "tdparse.py", line 436, in lidongfeat
    subtw, target_position, emp = traversaltree(conll[a],target,emp,'cmu') #returns relevant words to the target
  File "/scratch2/debate_tweets/sentiment/tdparse/src/utilities.py", line 175, in traversaltree
    positions = [[item for sublist in traversal.bfs_successors(G, target_position).values() for item in sublist] for target_position in target_positions]
AttributeError: 'generator' object has no attribute 'values'
/scratch/sjn-p2/anaconda/anaconda2/lib/python2.7/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
********************************************************************************
********************************************************************************
---Feature scaling
Scaling features
---Parameter tuning
/scratch/sjn-p2/anaconda/anaconda2/lib/python2.7/site-packages/numpy/lib/function_base.py:1110: RuntimeWarning: Mean of empty slice.
  avg = a.mean(axis)
/scratch/sjn-p2/anaconda/anaconda2/lib/python2.7/site-packages/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "liblinear.py", line 182, in <module>
    main(output_dir, args.ci, args.p)
  File "liblinear.py", line 138, in main
    tunec = TUNE(trfile,cv_trfile,cv_tfile,cv_pfile,cv_truey,id_train)
  File "liblinear.py", line 110, in TUNE
    tunec.append([ci] + CV(str(ci),trfile,cv_trfile,cv_tfile,cv_pfile,cv_truey,id_train))
  File "liblinear.py", line 83, in CV
    f1_two_list.append((metrics.f1_score(y_test, y_predicted, average=None)[0]+metrics.f1_score(y_test, y_predicted, average=None)[-1])/2)
IndexError: index 0 is out of bounds for axis 0 with size 0
```

```
[jalal@goku src]$ conda list gensim
# packages in environment at /scratch/sjn-p2/anaconda/anaconda2:
#
# Name                    Version                   Build  Channel
gensim                    1.0.1                     <pip>
```
How can I run your code on a single sentence and get results?

**Comment by bwang482** [comment]
Sorry for the late reply. Please make sure `networkx == 1.11`.
