### ISSUE TITLE
looking for the files can't open file ../data/election/output/training

### ISSUE THREAD

**Issue by monajalal** [bluemonk482/tdparse#6]
I get this and not sure how to fix it:

```
[jalal@goku src]$ ./run.sh election naiveseg sklearnSVM
extracting features for training
election training data
Traceback (most recent call last):
  File "naive-seg.py", line 430, in <module>
    main(args.d)
  File "naive-seg.py", line 413, in main
    x_train,y_train,id_train=features.elecfeat('../data/'+d+'/training/')
  File "naive-seg.py", line 401, in elecfeat
    x=x.reshape((len(y),len(x)/len(y)))
ZeroDivisionError: integer division or modulo by zero
/scratch/sjn-p2/anaconda/anaconda2/lib/python2.7/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
********************************************************************************
********************************************************************************
---Feature scaling
Scaling features
can't open file ../data/election/output/training
can't open file ../data/election/output/testing
loading features for training
loading features for testing
cross-validation
Traceback (most recent call last):
  File "sklearnSVM.py", line 103, in <module>
    main(output_dir)
  File "sklearnSVM.py", line 81, in main
    clf = CV(x_train, y_train) # Comment this if parameter tuning is not desired
  File "sklearnSVM.py", line 51, in CV
    grid_search.fit(x_train, y_train)
  File "/scratch/sjn-p2/anaconda/anaconda2/lib/python2.7/site-packages/sklearn/model_selection/_search.py", line 639, in fit
    cv.split(X, y, groups)))
  File "/scratch/sjn-p2/anaconda/anaconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 779, in __call__
    while self.dispatch_one_batch(iterator):
  File "/scratch/sjn-p2/anaconda/anaconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 625, in dispatch_one_batch
    self._dispatch(tasks)
  File "/scratch/sjn-p2/anaconda/anaconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 588, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/scratch/sjn-p2/anaconda/anaconda2/lib/python2.7/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 111, in apply_async
    result = ImmediateResult(func)
  File "/scratch/sjn-p2/anaconda/anaconda2/lib/python2.7/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 332, in __init__
    self.results = batch()
  File "/scratch/sjn-p2/anaconda/anaconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 131, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/scratch/sjn-p2/anaconda/anaconda2/lib/python2.7/site-packages/sklearn/model_selection/_validation.py", line 458, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/scratch/sjn-p2/anaconda/anaconda2/lib/python2.7/site-packages/sklearn/svm/classes.py", line 227, in fit
    dtype=np.float64, order="C")
  File "/scratch/sjn-p2/anaconda/anaconda2/lib/python2.7/site-packages/sklearn/utils/validation.py", line 573, in check_X_y
    ensure_min_features, warn_on_dtype, estimator)
  File "/scratch/sjn-p2/anaconda/anaconda2/lib/python2.7/site-packages/sklearn/utils/validation.py", line 462, in check_array
    context))
ValueError: Found array with 0 sample(s) (shape=(0, 1)) while a minimum of 1 is required.
```

**Comment by bwang482** [comment]
Sorry for the very late reply. Have you added the necessary directories as mentioned in https://github.com/bluemonk482/tdparse/tree/master/data/election?
