### ISSUE TITLE
Error in running liblinear.py

### ISSUE THREAD

**Issue by ankita240796** [bluemonk482/tdparse#7]
Hi @bluemonk482 

I tried to run your code using the instructions specified mentioned in your readme. I also have the gensim version as 1.0.1 as mentioned by you [here](https://github.com/bluemonk482/tdparse/issues/4#issuecomment-383151010). I face the following error and was unable to fix this:
```
Traceback (most recent call last):
  File "tdparse.py", line 531, in <module>
    main(args.d, args.conll1, args.conll2)
  File "tdparse.py", line 502, in main
    features=targettw()
  File "tdparse.py", line 114, in __init__
    self.w2v=gensim.models.Word2Vec.load(w2vf) 
  File "/home/ankita/.local/lib/python2.7/site-packages/gensim/models/word2vec.py", line 975, in load
    return super(Word2Vec, cls).load(*args, **kwargs)
  File "/home/ankita/.local/lib/python2.7/site-packages/gensim/models/base_any2vec.py", line 629, in load
    model = super(BaseWordEmbeddingsModel, cls).load(*args, **kwargs)
  File "/home/ankita/.local/lib/python2.7/site-packages/gensim/models/base_any2vec.py", line 278, in load
    return super(BaseAny2VecModel, cls).load(fname_or_handle, **kwargs)
  File "/home/ankita/.local/lib/python2.7/site-packages/gensim/utils.py", line 426, in load
    obj._load_specials(fname, mmap, compress, subname)
  File "/home/ankita/.local/lib/python2.7/site-packages/gensim/utils.py", line 469, in _load_specials
    setattr(self, attrib, val)
  File "/home/ankita/.local/lib/python2.7/site-packages/gensim/utils.py", line 1396, in new_func1
    stacklevel=2
DeprecationWarning: Call to deprecated `syn1` (Attribute will be removed in 4.0.0, use self.trainables.syn1 instead).
/home/ankita/.local/lib/python2.7/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
********************************************************************************
********************************************************************************
---Feature scaling
Scaling features
---Parameter tuning
/home/ankita/.local/lib/python2.7/site-packages/numpy/lib/function_base.py:1128: RuntimeWarning: Mean of empty slice.
  avg = a.mean(axis)
/home/ankita/.local/lib/python2.7/site-packages/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "liblinear.py", line 182, in <module>
    main(output_dir, args.ci, args.p)
  File "liblinear.py", line 138, in main
    tunec = TUNE(trfile,cv_trfile,cv_tfile,cv_pfile,cv_truey,id_train)
  File "liblinear.py", line 110, in TUNE
    tunec.append([ci] + CV(str(ci),trfile,cv_trfile,cv_tfile,cv_pfile,cv_truey,id_train))
  File "liblinear.py", line 83, in CV
    f1_two_list.append((metrics.f1_score(y_test, y_predicted, average=None)[0]+metrics.f1_score(y_test, y_predicted, average=None)[-1])/2)
IndexError: index 0 is out of bounds for axis 0 with size 0
```
Can you please guide me to solve this issue, Thanks!

**Comment by bwang482** [comment]
Hi @ankita240796 I couldn't reproduce the error. I have checked the version of some core libraries used in this work:
```
gensim.__version__ == 1.0.1
sklearn.__version__ == 0.18.1
networkx.__version__ == 1.11
```
Perhaps you are using the newer version of networkx?

**Comment by ankita240796** [comment]
Hi @bluemonk482, thanks for your reply.
I checked and updated the version but now I get this error.
```
Traceback (most recent call last):
  File "tdparse.py", line 531, in <module>
    main(args.d, args.conll1, args.conll2)
  File "tdparse.py", line 502, in main
    features=targettw()
  File "tdparse.py", line 114, in __init__
    self.w2v=gensim.models.Word2Vec.load(w2vf) 
  File "/home/ankita/.local/lib/python2.7/site-packages/gensim/models/word2vec.py", line 975, in load
    return super(Word2Vec, cls).load(*args, **kwargs)
  File "/home/ankita/.local/lib/python2.7/site-packages/gensim/models/base_any2vec.py", line 629, in load
    model = super(BaseWordEmbeddingsModel, cls).load(*args, **kwargs)
  File "/home/ankita/.local/lib/python2.7/site-packages/gensim/models/base_any2vec.py", line 278, in load
    return super(BaseAny2VecModel, cls).load(fname_or_handle, **kwargs)
  File "/home/ankita/.local/lib/python2.7/site-packages/gensim/utils.py", line 426, in load
    obj._load_specials(fname, mmap, compress, subname)
  File "/home/ankita/.local/lib/python2.7/site-packages/gensim/utils.py", line 469, in _load_specials
    setattr(self, attrib, val)
  File "/home/ankita/.local/lib/python2.7/site-packages/gensim/utils.py", line 1396, in new_func1
    stacklevel=2
DeprecationWarning: Call to deprecated `syn1` (Attribute will be removed in 4.0.0, use self.trainables.syn1 instead).
/home/ankita/.local/lib/python2.7/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
********************************************************************************
********************************************************************************
---Feature scaling
Scaling features
Traceback (most recent call last):
  File "liblinear.py", line 182, in <module>
    main(output_dir, args.ci, args.p)
  File "liblinear.py", line 132, in main
    scaling(output_dir)
  File "liblinear.py", line 16, in scaling
    with open("../data/"+output_dir+"/train.scale", "w") as outfile1:
IOError: [Errno 2] No such file or directory: '../data/lidong/output/train.scale'
```

**Comment by ankita240796** [comment]
Also there is no output directory in the folder ../data/lidong, so is it required to create an output folder there?

**Comment by bwang482** [comment]
Yes, as you see in the readme file here: https://github.com/bluemonk482/tdparse/blob/master/data/lidong/README

You should create the output directory in that folder. Hmm I should make it clearer.

**Comment by ankita240796** [comment]
Oh, my bad should have looked there. Also, now the error I get says:
```
can't open file ../data/lidong/output/training
can't open file ../data/lidong/output/testing

```

**Comment by ankita240796** [comment]
Hi @bluemonk482 the issue now is similar to this one: https://github.com/bluemonk482/tdparse/issues/4.
Can you please guide me here, Thanks!

**Comment by bluemonk482** [comment]
It should be more similar to https://github.com/bluemonk482/tdparse/issues/6, shouldn't it?

Can you pls provide the full error msg?

**Comment by bwang482** [comment]
@ankita240796 if it is the same issue in https://github.com/bluemonk482/tdparse/issues/4, then you should try to roll back gensim to maybe 0.13.4? Though I am using 1.0.1 and it is working for me. 

Can you provide the full error msg pls?

**Comment by ankita240796** [comment]
@bluemonk482 rolled back gensim to 0.13.4
Here is the log now:
```
Traceback (most recent call last):
  File "tdparse.py", line 531, in <module>
    main(args.d, args.conll1, args.conll2)
  File "tdparse.py", line 502, in main
    features=targettw()
  File "tdparse.py", line 116, in __init__
    self.lexicons=lexicon()
  File "tdparse.py", line 27, in __init__
    self.updateBinhliu(Bfiles)
  File "tdparse.py", line 70, in updateBinhliu
    lexBinh=self.Binhliu(Bfiles)
  File "tdparse.py", line 64, in Binhliu
    neg=np.loadtxt(filename[0],skiprows=1,dtype='string',comments=';')
  File "/home/ankita/.local/lib/python2.7/site-packages/numpy/lib/npyio.py", line 1092, in loadtxt
    for x in read_data(_loadtxt_chunksize):
  File "/home/ankita/.local/lib/python2.7/site-packages/numpy/lib/npyio.py", line 1007, in read_data
    for i, line in enumerate(itertools.chain([first_line], fh)):
  File "/usr/lib/python2.7/codecs.py", line 314, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xef in position 1433: invalid continuation byte
/usr/local/lib/python2.7/dist-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
********************************************************************************
********************************************************************************
---Feature scaling
Scaling features
can't open file ../data/lidong/output/training
can't open file ../data/lidong/output/testing
---Parameter tuning
/home/ankita/.local/lib/python2.7/site-packages/numpy/lib/function_base.py:1128: RuntimeWarning: Mean of empty slice.
  avg = a.mean(axis)
/home/ankita/.local/lib/python2.7/site-packages/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "liblinear.py", line 182, in <module>
    main(output_dir, args.ci, args.p)
  File "liblinear.py", line 138, in main
    tunec = TUNE(trfile,cv_trfile,cv_tfile,cv_pfile,cv_truey,id_train)
  File "liblinear.py", line 110, in TUNE
    tunec.append([ci] + CV(str(ci),trfile,cv_trfile,cv_tfile,cv_pfile,cv_truey,id_train))
  File "liblinear.py", line 83, in CV
    f1_two_list.append((metrics.f1_score(y_test, y_predicted, average=None)[0]+metrics.f1_score(y_test, y_predicted, average=None)[-1])/2)
IndexError: index 0 is out of bounds for axis 0 with size 0
```

**Comment by bwang482** [comment]
Somehow you're getting a decoding error from reading one of the lexicon files: `neg=np.loadtxt(filename[0],skiprows=1,dtype='string',comments=';')`. What machine are you running the program on? Maybe you can try the following things:

Option 1: Roll back your numpy to 1.11.0, which is the one I was using.

Option 2: 
`binhliu_neg_filename = codecs.open(filename[0], encoding = 'utf-8')
neg=np.loadtxt(binhliu_neg_filename, skiprows=1, dtype='string', comments=';')`

Option3: Find the text in that file that is giving you the coding error, and try to find the appropriate encoding to specify as an argument in `np.loadtxt()`.

Let me know how it goes.

**Comment by ankita240796** [comment]
I found the text in the file which was giving an error. The error was due to word `naïve` in file `negative-words.txt`. I replaced the word with `naive` and that fixed the issue for me. Thank you so much for such a quick response and all the guidance!

**Comment by bwang482** [comment]
No worries. Just out of curiosity, what machine are you running the program on? I have no issue with reading `naïve` on Ubuntu 1604.

**Comment by ankita240796** [comment]
I am on Ubuntu 16.04 as well.

**Comment by bwang482** [comment]
Hmm I think the original file was saved on a Windows machine with `cp1252` coding. The code below would resolve this w/o changing the lexicon file itself:

```
with codecs.open('negative-words.txt', encoding = 'cp1252') as neg_f:
    neg = [line.strip() for line in neg_f]
```

**Comment by ankita240796** [comment]
Hi @bluemonk482 
Ok, thanks a lot! :smile: 
Also if I want to get the output for some other tweets with annotated targets, how should I go about it?

**Comment by bwang482** [comment]
You should look at `tdparse/data/dataprocessing.py`, which has the input data processing functions for the lidong dataset as well as the election dataset. The two datasets have different format, and the election dataset has the indices for all targets. Maybe you want to write your own data processing function to suit your use.

**Comment by ankita240796** [comment]
Ok, got it! Thanks again :smile:
